plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    namespace = "com.alpinequest.app"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = "28.1.13356709"

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.alpinequest.app"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    signingConfigs {
        getByName("debug") {
            // CI passes one cached keystore so every build has the same
            // signature (see .github/workflows/flutter-build.yml).
            System.getenv("DEBUG_KEYSTORE")?.let { storeFile = file(it) }
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

flutter {
    source = "../.."
}

// Certificates of our own servers (app/certs/*.pem|*.crt, see certs/README.md)
// for MapLibre, which loads tiles and styles through Android's network stack:
// raw/server_ca.pem plus a network_security_config.xml that trusts it next
// to the system CAs. Dart's HTTP gets the same files as assets
// (lib/net/trusted_certificates.dart). Debug builds also allow cleartext
// (dev API over adb reverse) and user-installed CAs.
abstract class ServerCaResources : DefaultTask() {
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.NAME_ONLY)
    abstract val certs: ConfigurableFileCollection

    @get:Input
    abstract val debugBuild: Property<Boolean>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val out = outputDir.get().asFile
        out.deleteRecursively()
        val pems = certs.files.sortedBy { it.name }
        if (pems.isNotEmpty()) {
            val raw = File(out, "raw").apply { mkdirs() }
            File(raw, "server_ca.pem").writeText(pems.joinToString("\n") { it.readText().trim() } + "\n")
        }
        val ours = if (pems.isNotEmpty()) "\n            <certificates src=\"@raw/server_ca\" />" else ""
        val debug = debugBuild.get()
        val overrides = if (debug) """
    <debug-overrides>
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />$ours
        </trust-anchors>
    </debug-overrides>""" else ""
        File(out, "xml").apply { mkdirs() }.resolve("network_security_config.xml").writeText(
            """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by android/app/build.gradle.kts from app/certs/. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="$debug">
        <trust-anchors>
            <certificates src="system" />$ours
        </trust-anchors>
    </base-config>$overrides
</network-security-config>
""")
    }
}

androidComponents {
    onVariants { variant ->
        val task = tasks.register<ServerCaResources>("generate${variant.name.replaceFirstChar { it.uppercase() }}ServerCa") {
            certs.from(fileTree(rootProject.file("../certs")) { include("*.pem", "*.crt") })
            debugBuild.set(variant.buildType == "debug")
        }
        variant.sources.res?.addGeneratedSourceDirectory(task, ServerCaResources::outputDir)
    }
}

dependencies {
    // MainActivity sets MapView.prefetchZoomDelta on the maps maplibre_gl
    // creates. The plugin brings the SDK at run time; this only makes its
    // classes visible to the compiler. Keep the version equal to the one in
    // maplibre_gl's android/build.gradle.
    compileOnly("org.maplibre.gl:android-sdk-opengl:13.3.0")
}
